[default]
depends = ["emacs", "i3", "fish"]

[emacs.files]
"emacs/conf.org" = "~/.emacs.d/conf.org"
"emacs/init.el" = "~/.emacs.d/init.el"

[i3.files]
Xresources = "~/.Xresources"
autorandr = "~/.config/autorandr"
feh = "~/.fehbg"
# contains images, so should be symlinks
wallpapers = { target = "~/.config/wallpapers", type = "symbolic" }

[fish.files]
"config.fish" = "~/.config/fish/config.fish"