[default]
depends = ["emacs", "i3", "shells", "qmk", "misc"]

[emacs.files]
"emacs/conf.org" = "~/.emacs.d/conf.org"
"emacs/init.el" = "~/.emacs.d/init.el"
"emacs/spice" = "~/.emacs.d/spice"
aspell_dictionary = "~/.aspell.en.pws"

[i3.files]
i3 = "~/.config/i3/config"
xinitrc = "~/.xinitrc"
Xresources = "~/.Xresources"
autorandr = "~/.config/autorandr"
feh = "~/.fehbg"
# contains images, so should be symlinks
wallpapers = { target = "~/.config/wallpapers", type = "symbolic" }
i3status-rs = "~/.config/i3status-rs"

[shells.files]
"config.fish" = "~/.config/fish/config.fish"
"init.sage" = "~/.sage/init.sage"

[qmk.files]
"qmk/qmk.ini" = "~/.config/qmk/qmk.ini"

[misc.files]
global_gitignore = "~/.gitignore"
ssh = "~/.ssh/config"
#"userChrome.css" = "$FF_CHROME_PATH/chrome/userChrome.css"