theme = "slick"
icons = "awesome"

[[block]]
block = "custom"
command = "printf '\\uf1b2 '; and bedrock_count"
interval = 1

[[block]]
block = "cpu"
interval = 2
format = "{barchart} {utilization}"

[[block]]
block = "temperature"
collapsed = false

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used;G}/{mem_total;G}"
format_swap = "{swap_used;G}/{swap_total;G}"
clickable = true
interval = 1

[[block]]
block = "disk_space"
path = "/"
info_type = "used"
format = "/ {used}/{total}"
alert = 95
warning = 90

[[block]]
block = "custom"
command = "printf '\\uf074 '; and if ifconfig br0 | grep 'inet ' &> /dev/null; ifconfig br0 | grep 'inet ' | awk '{if(length($2)==0){printf\"\"}else{print $2}}'; else; printf ''; end"
interval = 2

# TODO: reintroduce status indicator for no connection
[[block]]
block = "custom"
command = "printf ' '; curl ipinfo.io/ip"
interval = 5

[[block]]
block = "custom"
command = "sh /home/notroot/.config/i3status-rs/date.sh" # ordinals
interval = 1
on_click = "exec emacs -f \"calendar\""