# I'm not using good toml parsing so this has zero error-checking
# If a package is not specified here, assume always update
# Packeges here require an extra pacaur call if appropriate, so query lightly

# update_on options are "always", "major", "minor", "patch", "never", and empty/unmarked (default, never update)

[ungoogled-chromium] # specify a package name
update_on = "never"

# I maintain these and know what's broken on my machine :)
[linux-x570-vfio-openrgb-sm2262+sm2263]
update_on = "never"
[linux-x570-vfio-openrgb-sm2262+sm2263-docs]
update_on = "never"
[linux-x570-vfio-openrgb-sm2262+sm2263-headers]
update_on = "never"

# Stable doesn't work and this would also require a change in VM so sticking with what's stable
[looking-glass]
update_on = "never"
[looking-glass-host]
update_on = "never"
[looking-glass-module-dkms]
update_on = "never"
[obs-plugin-looking-glass]
update_on = "never"

# qmk requires a specific avr-gcc version
[avr-gcc]
update_on = "never"
